[env:Native]
platform = native
lib_deps =
  lordmax2/klevebrand-all-drone-controller-core@^1.4.6
  fabiobatsilva/ArduinoFake@^0.4.0
build_flags =
  -std=gnu++11
  -D SIMULATION_MODE=1
  -g3 -Og
lib_compat_mode = off
build_type = debug
monitor_filters = default, log2file